[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    Access-Control-Allow-Origin = "*"
